CREATE TABLE IF NOT EXISTS `custom_reviews` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `AUTHOR` VARCHAR(100) NOT NULL,
    `TEXT` TEXT NOT NULL,
    `RATING` INT NOT NULL CHECK (RATING >= 1 AND RATING <= 5),
    `CREATED_AT` DATETIME NOT NULL,
    `USER_ID` INT NULL,
    PRIMARY KEY (ID),
    INDEX ix_created_at (CREATED_AT)
);
